pipeline {
    agent any

    environment {
        IMAGE_NAME = "nikhilsimha112/shopping-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sainikhil115/pythonshopping.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'sainikhil115',
                    passwordVariable: 'Ni9182271640@123'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}

